on:
  release:
    types: [created]
jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        arch: ['x64', 'arm64']
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - run: sudo xcode-select -switch /Applications/Xcode_13.1.app

      - name: Build Qode binary
        run: node ./qode/build.js
        env:
          TARGET_ARCH: ${{ matrix.arch }}

      - name: Compress files
        uses: a7ul/tar-action@v1.0.2
        with:
          command: c
          cwd: ./out/Release
          files: |
            ./qode
          outPath: ${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz

      - uses: actions/upload-artifact@v1
        with:
          name: ${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz
          path: ${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz"]'
